#!/bin/bash

source $(dirname $0)/DOCKER/scripts/help.sh
source $(dirname $0)/DOCKER/scripts/utils.sh
source $(dirname $0)/DOCKER/scripts/sites.sh
source $(dirname $0)/DOCKER/scripts/supervisor.sh
source $(dirname $0)/DOCKER/scripts/database.sh
source $(dirname $0)/DOCKER/scripts/installer.sh
source $(dirname $0)/DOCKER/scripts/docker.sh
source $(dirname $0)/DOCKER/scripts/backup.sh
source $(dirname $0)/DOCKER/scripts/generate-override.sh
source $(dirname $0)/DOCKER/scripts/recreate-ssl.sh

openCD $0

set -a && source DOCKER/.env && set +a
shift $((OPTIND -1))

subcommand=$1; shift

case "$subcommand" in
  up)
    startExec0000=$(date +'%s')
    header
    ln
    colorize $WHITE "🗑 $LIGHT_RED$(rm -v DOCKER/docker-compose.override.yml)"
    docker_up
    generate-override
    clear
    docker_up
    timeExec=$(diffTime "$startExec0000")
    CUSTOM_RIGHT $WHITE "Done all:" $LIGHT_GRAY "$timeExec" $WHITE "✔" "." "✔" 0
    docker_bash "homelab-database" "logs-chmod:root"
    ln
    runonce_fn
    ln
    www
    footer
    if [ -x "$(command -v notify-send)" ]; then
      startup=$(cat logs/startup.pid)
      startupDate=$(diffTime "$startup")
      /usr/bin/notify-send "Compose use: ${COMPOSE_PROJECT_NAME^^}" "Startup containers | ${startupDate}" -a "HomeLab" -i process-working-symbolic -t 8000 1>/dev/null 2>&1
    fi
  ;;
  ps)
    header
    ln
    docker_ps
    footer
  ;;
  runonce)
    header
    ln
    runonce_fn
    footer
  ;;
  restart)
    header
    startup
    ln
    docker_bash "homelab-php7" "logs-chmod:root"
    docker_restart
    ln
    runonce_fn
    footer
  ;;
  clear)  
    header
    startup
    ln
    docker_bash "homelab-php7" "logs-chmod:root"
    clearLogs
    openCD $0 
    if [ -f "logs/startup.pid" ]; then
      ln
      docker_restart
      ln
      runonce_fn
    fi
    footer
  ;;
  help)
    header
    ln
    help "$@"
    footer
  ;;
  install)
    header
    ln
    installer
    footer
  ;;
  logs)
    header
    ln
    docker_logs "$@"
    footer
  ;;
  bash)
    docker_bash "$@" "bash:root"
  ;;
  dumpsdb)
    header
    ln
    dumpsdb "$@"
    footer
  ;;
  dropdb)
    header
    dropdb "$@"
    ln
    footer
  ;;
  createdb)
    header
    createdb "$@"
    ln
    footer
  ;;
  importdb)
    header
    importdb "$@"
    ln
    footer
  ;;
  php8)
    docker_bash "homelab-php8" "bash:root"
  ;;
  php7)
    docker_bash "homelab-php7" "bash:root"
  ;;
  php8-usr)
    docker_bash "homelab-php8" "bash:${USERNAME}"
  ;;
  php7-usr)
    docker_bash "homelab-php7" "bash:${USERNAME}"
  ;;
  php8-cli)
    docker_bash "homelab-php8" "php:${USERNAME}" $@
  ;;
  php7-cli)
    docker_bash "homelab-php7" "php:${USERNAME}" $@
  ;;
  php8-composer)
    docker_bash "homelab-php8" "composer:${USERNAME}" $@
  ;;
  php7-composer)
    docker_bash "homelab-php7" "composer:${USERNAME}" $@
  ;;
  recreate-ssl)
    header
    ln
    recreate-ssl
    footer
  ;;
  newsubdomain)
    header
    ln
    newsite 0 $@
    footer
  ;;
  newdomain)
    header
    ln
    newsite 1 $@
    footer
  ;;
  legacydomain)
    header
    ln
    newsite 2 $@
    footer
  ;;
  legacysubdomain)
    header
    ln
    newsite 3 $@
    footer
  ;;
  delsubdomain)
    header
    ln
    delsite 0 $@
    footer
  ;;
  deldomain)
    header
    ln
    delsite 1 $@
    footer
  ;;
  listsite)
    header
    ln
    www
    footer
  ;;
  newsupervisor)
    header
    ln
    newSupervisor $@
    footer
  ;;
  delsupervisor)
    header
    ln
    delSupervisor $@
    footer
  ;;
  listsupervisor)
    header
    ln
    listSupervisor $@
    footer
  ;;
  startsupervisor)
    header
    ln
    startedSupervisor $@
    footer
  ;;
  down)
    header
    docker_bash "homelab-php8" "logs-chmod:root"
    docker_bash "homelab-php7" "logs-chmod:root"
    docker_bash "homelab-database" "logs-chmod:root"
    docker_down "$@"
    footer
  ;;
  backup)
    header
    backup
    footer
  ;;
  status)
    header
    status
    footer
  ;;
  makealias)
    header
    makealias
    footer
  ;;
  *)
    header
    ln
    openCD $0 
    if [ -f "logs/startup.pid" ]; then
      CUSTOM_RIGHT $LIGHT_RED 'Invalid command' $LIGHT_RED "'$subcommand'" $WHITE "⮡" "." "✘" 0
      ln
    fi
    help "$@"
    footer
  ;;
esac

