#!/bin/bash

source $(dirname $0)/DOCKER/scripts/help.sh
source $(dirname $0)/DOCKER/scripts/utils.sh
source $(dirname $0)/DOCKER/scripts/sites.sh
source $(dirname $0)/DOCKER/scripts/supervisor.sh
source $(dirname $0)/DOCKER/scripts/database.sh
source $(dirname $0)/DOCKER/scripts/installer.sh
source $(dirname $0)/DOCKER/scripts/docker.sh
source $(dirname $0)/DOCKER/scripts/backup.sh
source $(dirname $0)/DOCKER/scripts/generate-override.sh
source $(dirname $0)/DOCKER/scripts/recreate-ssl.sh

openCD $0

set -a && source DOCKER/.env && set +a
shift $((OPTIND -1))

subcommand=$1; shift

case "$subcommand" in
  up)
    header
    ln
    rm -v DOCKER/docker-compose.override.yml
    docker_up
    generate-override
    clear
    docker_up
    docker_bash "homelab-mariadb" "logs-chmod"
    ln
    startedSupervisor
    www
    footer
  ;;
  ps)
    header
    ln
    docker_ps
    footer
  ;;
  restart)
    header
    startup
    ln
    docker_restart
    ln
    startedSupervisor
    footer
  ;;
  clear)  
    header
    startup
    ln
    clearLogs
    openCD $0 
    if [ -f "logs/startup.pid" ]; then
      ln
      docker_restart
      ln
      startedSupervisor
    fi
    footer
  ;;
  help)
    header
    ln
    help "$@"
    footer
  ;;
  install)
    header
    ln
    installer
    footer
  ;;
  logs)
    header
    ln
    docker_logs "$@"
    footer
  ;;
  bash)
    docker_bash "$@" "bash"
  ;;
  dumpsdb)
    header
    ln
    dumpsdb "$@"
    footer
  ;;
  dropdb)
    header
    dropdb "$@"
    ln
    footer
  ;;
  createdb)
    header
    createdb "$@"
    ln
    footer
  ;;
  importdb)
    header
    importdb "$@"
    ln
    footer
  ;;
  php8)
    docker_bash "homelab-php8" "bash"
  ;;
  php7)
    docker_bash "homelab-php7" "bash"
  ;;
  php8-cli)
    docker_bash "homelab-php8" "php" $@
  ;;
  php7-cli)
    docker_bash "homelab-php7" "php" $@
  ;;
  php8-composer)
    docker_bash "homelab-php8" "composer" $@
  ;;
  php7-composer)
    docker_bash "homelab-php7" "composer" $@
  ;;
  php8-usr)
    docker_bash "homelab-php8" "bash" "${USERNAME}"
  ;;
  php7-usr)
    docker_bash "homelab-php7" "bash" "${USERNAME}"
  ;;
  recreate-ssl)
    header
    ln
    recreate-ssl
    footer
  ;;
  newsubdomain)
    header
    ln
    newsite 0 $@
    footer
  ;;
  newdomain)
    header
    ln
    newsite 1 $@
    footer
  ;;
  legacydomain)
    header
    ln
    newsite 2 $@
    footer
  ;;
  legacysubdomain)
    header
    ln
    newsite 3 $@
    footer
  ;;
  delsubdomain)
    header
    ln
    delsite 0 $@
    footer
  ;;
  deldomain)
    header
    ln
    delsite 1 $@
    footer
  ;;
  listsite)
    header
    ln
    www
    footer
  ;;
  newsupervisor)
    header
    ln
    newSupervisor $@
    footer
  ;;
  delsupervisor)
    header
    ln
    delSupervisor $@
    footer
  ;;
  listsupervisor)
    header
    ln
    listSupervisor $@
    footer
  ;;
  down)
    header
    docker_down "$@"
    footer
  ;;
  backup)
    header
    backup
    footer
  ;;
  *)
    header
    ln
    openCD $0 
    if [ -f "logs/startup.pid" ]; then
      CUSTOM_RIGHT $LIGHT_RED 'Invalid command' $LIGHT_RED "'$subcommand'" $WHITE "⮡" "." "✘" 0
      ln
    fi
    help "$@"
    footer
  ;;
esac

