#!/bin/bash

source $(dirname $0)/DOCKER/scripts/help.sh
source $(dirname $0)/DOCKER/scripts/utils.sh
source $(dirname $0)/DOCKER/scripts/sites.sh
source $(dirname $0)/DOCKER/scripts/installer.sh
source $(dirname $0)/DOCKER/scripts/docker.sh

cd $(dirname $0)
set -a && source DOCKER/.env && set +a
shift $((OPTIND -1))

subcommand=$1; shift

case "$subcommand" in
  up)
    header
    docker_up
    ln
    www
    footer
  ;;
  ps)
    header
    docker_ps
    footer
  ;;
  restart)
    header
    docker_restart
    footer
  ;;
  clear)  
    header
    clear
    cd $(dirname $0)
    if [ -f "logs/startup.pid" ]; then
      ln
      docker_restart
    fi
    footer
  ;;
  help)
    header
    help
    footer
  ;;
  install)
    header
    installer
    footer
  ;;
  logs)
    header
    docker_logs "$@"
    footer
  ;;
  bash)
    docker_bash "$@" "bash"
  ;;
  dumps)
    header
    cd $(dirname $0)
    if [ -f "logs/startup.pid" ]; then
      R1 $YELLOW "Dumping database: " $WHITE '▾' "."
      docker_bash "homelab-mariadb" "mariadb --version"
      R1 $GREEN "DUMPS: $(dirname $0)/dumpSQL" $WHITE '✔' "."
      docker_bash "homelab-mariadb" "dump_databases"
    else
      CUSTOM $NC 'Dumping database' $LIGTH_CYAN "There is nothing to do" $WHITE "☐" " " "☐" 0
      ln
      help
    fi
    footer
  ;;
  php8)
    docker_bash "homelab-php8" "bash"
  ;;
  php7)
    docker_bash "homelab-php7" "bash"
  ;;
  php8-cli)
    docker_bash "homelab-php8" "php" $@
  ;;
  php7-cli)
    docker_bash "homelab-php7" "php" $@
  ;;
  php8-usr)
    docker_bash "homelab-php8" "bash" "${USERNAME}"
  ;;
  php7-usr)
    docker_bash "homelab-php7" "bash" "${USERNAME}"
  ;;
  newsite)
    header
    newsite $@
    footer
  ;;
  listsite)
    header
    www
    footer
  ;;
  down)
    header
    docker_down "$@"
    footer
  ;;
  *)
    header
    cd $(dirname $0)
    if [ -f "logs/startup.pid" ]; then
      R1 $RED "Invalid command" $LIGTH_RED "✘" "."
      colorize $LIGTH_RED "⮡ \'$subcommand\'   "
      ln
    fi
    help
    footer
  ;;
esac
