#!/bin/bash
php -v > /var/log/php/startup-$(hostname).log
echo -e "----------" >> /var/log/php/startup-$(hostname).log
date >> /var/log/php/startup-$(hostname).log
echo -e "----------" >> /var/log/php/startup-$(hostname).log
hostname >> /var/log/php/startup-$(hostname).log
grep '^PRETTY_NAME' /etc/os-release | cut -d '"' -f 2 >> /var/log/php/startup-$(hostname).log 2>&1
/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf