services:
  ############################
  # Databases
  ############################
  homelab-database:
    image: mariadb:latest
    container_name: homelab-database
    hostname: database-${COMPOSE_PROJECT_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      TZ: ${TIMEZONE}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_DATABASE}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - MariadbVol:/var/lib/mysql
      - "../logs/database:/var/log/mysql:rw"
      - "../config/database-initdb:/docker-entrypoint-initdb.d:rw"
      - "./images/database/conf.d:/etc/mysql/conf.d"
      - "../dumpSQL:/root/dumps:rw"
      - "./images/database/logs-chmod.sh:/usr/bin/logs-chmod"
      - "./images/database/opt:/opt/db:rw"
    networks:
      - homelab-network


  homelab-adminer:    
    build:
      context: ./images/adminer
      dockerfile: Dockerfile
    container_name: homelab-adminer
    image: homelab:adminer
    hostname: adminer-client
    ports:
      - 8080
    links:
      - homelab-database
    environment:
      ADMINER_DEFAULT_SYSTEM: mariadb
      ADMINER_DEFAULT_SERVER: "homelab-database"
      ADMINER_DEFAULT_USERNAME: "root"
      ADMINER_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TIMEZONE}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - homelab-network

  ############################
  # Caches
  ############################
  homelab-redis:
    image: redis:alpine
    container_name: homelab-redis
    ports:
      - ${REDIS_PORT}:6379
    environment:
      TZ: ${TIMEZONE}
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - RedisVol:/data
    networks:
      - homelab-network

  homelab-redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: homelab-redis-commander
    environment:
      - REDIS_HOSTS=local:homelab-redis:${REDIS_PORT}
      - HTTP_USER=${REDIS_COMMANDER_USER}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD}
    ports:
      - 9080:8081
    networks:
      - homelab-network
    depends_on:
      - homelab-redis

  ############################
  # Mailtramp
  ############################
  homelab-mailhog:
    image: mailhog/mailhog
    container_name: homelab-mailhog
    ports:
      - ${MAILHOG_SMTP_PORT}:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - homelab-network

  ############################
  # Webserver
  ############################
  homelab-webserver:
    container_name: homelab-webserver
    image: nginx:alpine
    tty: true
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../logs/nginx:/var/log/nginx:rw
      - ../www:/var/www:rw
      - ./images/nginx/entrypoint:/docker-entrypoint.d:rw
      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../config/nginx-sites:/etc/nginx/sites-available:rw
      - ./certs:/certs
    hostname: webserver-${COMPOSE_PROJECT_NAME}
    depends_on:
      - homelab-database
      - homelab-php7
      - homelab-php8
      - homelab-adminer
      - homelab-redis-commander
    extra_hosts:
      - "docker.internal:host-gateway"
    networks:
      homelab-network:
        aliases:
          - homelab-php7
          - homelab-php8
          - homelab-adminer
          - homelab-redis-commander

  ############################
  # Applications
  ############################
  homelab-php7:
    build:
      context: ./images/php/
      dockerfile: Dockerfile
      args:
        user: ${USERNAME}
        uid: ${USER_UID}
        port: 9007
        phpVersion: ${phpVersion7}
    environment:
      TZ: ${TIMEZONE}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_DATABASE: ${DATABASE_DATABASE}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_IMAGES: MariaDB
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    container_name: homelab-php7
    image: homelab:${phpVersion7}-custom
    working_dir: /var/www
    tty: true
    hostname: php7-${COMPOSE_PROJECT_NAME}
    volumes:
      - ../logs/php7:/var/log/php:rw
      - ../logs/sites-logs:/var/log/sites-logs:rw
      - ../www:/var/www:rw
      - ../logs/supervisor:/var/log/supervisor:rw
      - ../config/supervisor/php7:/etc/supervisor/conf.d:rw
      - ../config/composer/php7/root:/root/.config/composer:rw
      - ../config/composer/php7/${USERNAME}:/home/${USERNAME}/.config/composer:rw
      - ./images/php/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./images/php/ini/defaults.ini:/usr/local/etc/php/conf.d/defaults.ini
      - ./certs/mkcert:/root/.local/share/mkcert
    depends_on:
      - homelab-database
      - homelab-redis
      - homelab-mailhog
    dns:
      - 8.8.4.4
      - 8.8.8.8
    networks:
      homelab-network:
        aliases:
          - homelab-webserver
          - homelab-php8
          - homelab-mailhog

  homelab-php8:
    build:
      context: ./images/php/
      dockerfile: Dockerfile
      args:
        user: ${USERNAME}
        uid: ${USER_UID}
        port: 9008
        phpVersion: ${phpVersion8}
    environment:
      TZ: ${TIMEZONE}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_DATABASE: ${DATABASE_DATABASE}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_IMAGES: MariaDB
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    container_name: homelab-php8
    image: homelab:${phpVersion8}-custom
    working_dir: /var/www
    hostname: php8-${COMPOSE_PROJECT_NAME}
    tty: true
    volumes:
      - ../logs/php8:/var/log/php:rw
      - ../logs/sites-logs:/var/log/sites-logs:rw
      - ../logs/supervisor:/var/log/supervisor:rw
      - ../www:/var/www:rw
      - ../config/supervisor/php8:/etc/supervisor/conf.d:rw
      - ../config/composer/php8/root:/root/.config/composer:rw
      - ../config/composer/php8/${USERNAME}:/home/${USERNAME}/.config/composer:rw
      - ./images/php/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./images/php/ini/defaults.ini:/usr/local/etc/php/conf.d/defaults.ini
      - ./certs/mkcert:/root/.local/share/mkcert
    depends_on:
      - homelab-database
      - homelab-redis
      - homelab-mailhog
    dns:
      - 8.8.4.4
      - 8.8.8.8
    networks:
      homelab-network:
        aliases:
          - homelab-webserver
          - homelab-php7
          - homelab-mailhog

volumes:
  MariadbVol:
  RedisVol:

networks:
  homelab-network:
    driver: bridge
    enable_ipv6: false
    internal: false
    attachable: true
    labels:
      com.docker.network.bridge.name: "homelab-bridge"

    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
      com.docker.network.driver.mtu: "1500"